<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

### 1.1 Let’s compare

In [4]:
import numpy as np

py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

np_super_name = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                 }

### 1.2 Accessing data from a list (or array)

In [8]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

print(py_real_names[0])
print(py_super_names[0])
print(py_super_names[2])
print(py_super_names[-1])

Natasha Romanoff
Black Widow
Doctor Strange
Doctor Strange


### 1.3 Accessing data from a dictionary

In [11]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }
print(superhero_info["Natasha Romanoff"])

superhero_info.keys()
superhero_info.values()

Black Widow


dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

### 1.4 Higher dimensional lists

In [13]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                    ['Tony Stark', 'Iron Man'],
                    ['Stephen Strange', 'Doctor Strange']]


## 2 Lists vs. Arrays

### 2.1 Size

In [4]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

len(py_list_2d)
len(np_array_2d)

np_array_2d.shape

(10, 2)

### 2.2 Arrays are fussy about type

In [5]:
py_list = [1, 1.5, 'A']
np.array(py_list)


array(['1', '1.5', 'A'], dtype='<U32')

### 2.3 Adding a number

In [7]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

np_array + 10


array([11, 12, 13, 14, 15])

### 2.4 Adding another list

In [10]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

py_list_1 + py_list_2
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

### 2.5 Multiplying by a Number

In [12]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

py_list*2
np_array*2

array([ 2,  4,  6,  8, 10])

### 2.6 Squaring

In [13]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

np_array**2

array([ 1,  4,  9, 16, 25])

### 2.7 Asking questions

In [16]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

py_list == 3
np_array == 3
np_array > 3

array([False, False, False,  True,  True])

### 2.8 Mathematics

In [23]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

sum(py_list)
max(py_list)
min(py_list)    

np_array.sum()
np_array.mean()
np_array.max()
np_array.min()

1

## Exercise 1 :  Total recall?

In [27]:
print("1. both are used to store data & the way to use len() is the same")

print("2. to find the sum of the numbers in the list are different; operation on list works on the whole list, while operation on array works on individual elements")

print("3. it uses a key and a value associated to the key to relate 2 lists to one another")

1. both are used to store data & the way to use len() is the same
2. to find the sum of the numbers in the list are different; operation on list works on the whole list, while operation on array works on individual elements
3. it uses a key and a value associated to the key to relate 2 lists to one another


## Exercise 2 :  Index me

In [29]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
print(py_list[0])   # Prints 'a1'
print(py_list[2])   # Prints 'c3'
print(py_list[4])   # Prints 'e5'
print(py_list[6])   # Prints 'g7'
print(py_list[8])   # Prints 'i9'




a1
c3
e5
g7
i9


## Exercise 3 :  Capitalise Heros

In [32]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

superhero_info['Tony Stark'] = superhero_info['Tony Stark'].upper()                  
superhero_info['Natasha Romanoff'] = superhero_info['Natasha Romanoff'].upper()
superhero_info['Stephen Strange'] = superhero_info['Stephen Strange'].upper()

print(superhero_info["Natasha Romanoff"])
print(superhero_info["Tony Stark"])
print(superhero_info["Stephen Strange"])

BLACK WIDOW
IRON MAN
DOCTOR STRANGE


## Exercise 4 :  How many ones

In [40]:
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]                  


np_array = np.array(numbers)
sum(np_array == 1)

9